# Generated by Django 6.0.1 on 2026-01-19 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_options_alter_location_uuid_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationrole',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='locationrole',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='locationrole',
            index=models.Index(fields=['uuid', 'name'], name='people_loca_uuid_a36877_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['uuid', 'name'], name='people_pers_uuid_649ae4_idx'),
        ),
    ]
