# Generated by Django 6.0.1 on 2026-01-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_locationrole_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people/%Y/%m/%d'),
        ),
    ]
