# Generated by Django 6.0.1 on 2026-01-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_image'),
        ('people', '0003_person_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='people_pers_uuid_649ae4_idx',
        ),
        migrations.AddField(
            model_name='person',
            name='locations',
            field=models.ManyToManyField(related_name='people', through='people.LocationRole', to='locations.location'),
        ),
    ]
