# Generated by Django 6.0.1 on 2026-01-19 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='location',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['uuid', 'name'], name='locations_l_uuid_153c39_idx'),
        ),
    ]
