# Generated by Django 6.0.1 on 2026-01-19 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_location_image'),
        ('people', '0004_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('not_given', 'Not Given'), ('given', 'Given'), ('not_started', 'Not Started'), ('abandoned', 'Abandoned'), ('in_progress', 'In Progress'), ('failed', 'Failed'), ('succeeded', 'Succeeded'), ('ended', 'Ended')], default='not_given', max_length=24)),
                ('given_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests_given_here', to='locations.location')),
                ('giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests_given', to='people.person')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests_here', to='locations.location')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['uuid', 'name'], name='quests_ques_uuid_6be05a_idx')],
            },
        ),
    ]
