# Generated by Django 6.0.1 on 2026-01-19 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_options_and_more'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('not_given', 'Not Given'), ('given', 'Given'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('failed', 'Failed'), ('succeeded', 'Succeeded'), ('abandoned', 'Abandoned'), ('ended', 'Ended')], default='not_given', max_length=24),
        ),
        migrations.CreateModel(
            name='QuestCharacter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.quest')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='characters',
            field=models.ManyToManyField(related_name='quest_appearances', through='quests.QuestCharacter', to='people.person'),
        ),
        migrations.AddIndex(
            model_name='questcharacter',
            index=models.Index(fields=['uuid', 'name'], name='quests_ques_uuid_308c24_idx'),
        ),
    ]
